// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: contact_quote.
// - Entity ID: 102019c1341eb64763ab1be2109ef48dc96.
// - Entity Version: 102019ca3b1cabc7898927a85ff5704f554.
// - Task ID: 69a2bcb57fa07e0914a012e2.
// - Task Root ID: 697dc27eb1f12e575600d68f.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ContactQuoteServiceType
 */
export enum ContactQuoteServiceType {
  Unspecified = 0,
  DomesticElectrical = 1,
  CommercialElectrical = 2,
  EmergencyCallouts = 3,
}



/**
 * Interface for ContactQuoteModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ContactQuoteModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  name: string;
  email: string;
  phone: string;
  service_type: ContactQuoteServiceType;
  message: string;
}

/**
 * ORM class for ContactQuote entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ContactQuoteORM {
  private static instance: ContactQuoteORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c1341eb64763ab1be2109ef48dc96';
    this.entityName = 'contact_quote';
    this.entityVersion = '102019ca3b1cabc7898927a85ff5704f554';
    this.taskId = '69a2bcb57fa07e0914a012e2';
    this.taskRootId = '697dc27eb1f12e575600d68f';
  }

  /**
   * Get singleton instance of ContactQuoteORM
   */
  public static getInstance(): ContactQuoteORM {
    if (!ContactQuoteORM.instance) {
      ContactQuoteORM.instance = new ContactQuoteORM();
    }
    
    return ContactQuoteORM.instance;
  }

  /**
   * Get contact_quote by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getContactQuoteByIDs(ids: string[]): Promise<ContactQuoteModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contact_quote by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteContactQuoteByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all ContactQuote records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllContactQuote(): Promise<ContactQuoteModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ContactQuote record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertContactQuote(data: ContactQuoteModel[]): Promise<ContactQuoteModel[]> {
    const structured = data.map((item) => CreateData(ContactQuoteModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ContactQuote records
   */
  async purgeAllContactQuote(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ContactQuote records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listContactQuote(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ContactQuoteModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get contact_quote by Id index
   * This function gets data by index.
   */
  async getContactQuoteById(
    id: string,
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contact_quote by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContactQuoteById(
    id: string,
    data: ContactQuoteModel
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexId(
      id
    );

    const values = ContactQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contact_quote by Id index
   */
  async deleteContactQuoteById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get contact_quote by DataCreator index
   * This function gets data by index.
   */
  async getContactQuoteByDataCreator(
    data_creator: string,
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contact_quote by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContactQuoteByDataCreator(
    data_creator: string,
    data: ContactQuoteModel
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ContactQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contact_quote by DataCreator index
   */
  async deleteContactQuoteByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get contact_quote by DataUpdater index
   * This function gets data by index.
   */
  async getContactQuoteByDataUpdater(
    data_updater: string,
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contact_quote by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContactQuoteByDataUpdater(
    data_updater: string,
    data: ContactQuoteModel
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ContactQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contact_quote by DataUpdater index
   */
  async deleteContactQuoteByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get contact_quote by Email index
   * This function gets data by index.
   */
  async getContactQuoteByEmail(
    email: string,
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contact_quote by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContactQuoteByEmail(
    email: string,
    data: ContactQuoteModel
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = ContactQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contact_quote by Email index
   */
  async deleteContactQuoteByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get contact_quote by CreateTime index
   * This function gets data by index.
   */
  async getContactQuoteByCreateTime(
    create_time: string,
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contact_quote by CreateTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContactQuoteByCreateTime(
    create_time: string,
    data: ContactQuoteModel
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const values = ContactQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contact_quote by CreateTime index
   */
  async deleteContactQuoteByCreateTime(
    create_time: string
  ): Promise<void> {
    const index = createIndexCreateTime(
      create_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get contact_quote by ServiceType index
   * This function gets data by index.
   */
  async getContactQuoteByServiceType(
    service_type: ContactQuoteServiceType,
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexServiceType(
      service_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contact_quote by ServiceType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContactQuoteByServiceType(
    service_type: ContactQuoteServiceType,
    data: ContactQuoteModel
  ): Promise<ContactQuoteModel[]> {
    const index = createIndexServiceType(
      service_type
    );

    const values = ContactQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contact_quote by ServiceType index
   */
  async deleteContactQuoteByServiceType(
    service_type: ContactQuoteServiceType
  ): Promise<void> {
    const index = createIndexServiceType(
      service_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ContactQuoteModel data array
   */
  private resultToData(values: Data[]): ContactQuoteModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ContactQuoteModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ContactQuoteModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ContactQuoteModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ContactQuoteModel => item !== null);
  }
}

/**
 * Convert ContactQuoteModel data to Value array
 */
function ContactQuoteModelToValues(data: ContactQuoteModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'phone', type: DataType.string, defaultValue: '' },
    { key: 'service_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'message', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ContactQuoteModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ContactQuoteModel data
 */
function ContactQuoteModelFromValues(values: Value[]): ContactQuoteModel {
  const data: Partial<ContactQuoteModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'phone':
        data.phone = ParseValue(value, DataType.string) as string;
        break;
      case 'service_type':
        data.service_type = ParseValue(value, DataType.enumeration) as ContactQuoteServiceType;
        break;
      case 'message':
        data.message = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ContactQuoteModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}
/**
 * Create index for CreateTime fields
 */
function createIndexCreateTime(
  create_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
  ];

  return {
    fields: ['create_time'],
    values
  };
}
/**
 * Create index for ServiceType fields
 */
function createIndexServiceType(
  service_type: ContactQuoteServiceType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, service_type, 'service_type'),
  ];

  return {
    fields: ['service_type'],
    values
  };
}

export default ContactQuoteORM;