/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewsImport } from './routes/news'
import { Route as IndexImport } from './routes/index'
import { Route as AdminQuotesImport } from './routes/admin.quotes'
import { Route as AdminArticlesImport } from './routes/admin.articles'

// Create/Update Routes

const NewsRoute = NewsImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminQuotesRoute = AdminQuotesImport.update({
  id: '/admin/quotes',
  path: '/admin/quotes',
  getParentRoute: () => rootRoute,
} as any)

const AdminArticlesRoute = AdminArticlesImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsImport
      parentRoute: typeof rootRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesImport
      parentRoute: typeof rootRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/quotes': typeof AdminQuotesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/quotes': typeof AdminQuotesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/quotes': typeof AdminQuotesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/news' | '/admin/articles' | '/admin/quotes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/news' | '/admin/articles' | '/admin/quotes'
  id: '__root__' | '/' | '/news' | '/admin/articles' | '/admin/quotes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminQuotesRoute: AdminQuotesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/news",
        "/admin/articles",
        "/admin/quotes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/news": {
      "filePath": "news.tsx"
    },
    "/admin/articles": {
      "filePath": "admin.articles.tsx"
    },
    "/admin/quotes": {
      "filePath": "admin.quotes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
